blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>",
        views.post_detail,
        name="post_detail",
    ),
    # path(
    #     "<int:year>/<int:month>/<int:day>/<slug:post>",
    #     views.PostDetailView.as_view(),
    #     name="post_detail",
    # ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

blog_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]


urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique_for_date="publish")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_post")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT
    )

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"]),
        ]

    def __str__(self) -> str:
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 3
#     template_name = "blog/post/list.html"


# class PostDetailView(DetailView):
#     model = Post
#     template_name = "blog/post/detail.html"
#     context_object_name = "post"

#     def get_object(self):
#         return get_object_or_404(
#             Post,
#             status=Post.Status.PUBLISHED,
#             slug=self.kwargs.get("post"),
#             publish__year=self.kwargs.get("year"),
#             publish__month=self.kwargs.get("month"),
#             publish__day=self.kwargs.get("day"),
#         )


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get("page", 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        # if out of range, deliver the last page of result.
        posts = paginator.page(paginator.num_pages)
    context = {"posts": posts, "tag": tag}
    return render(request, "blog/post/list.html", context)


def post_detail(request, year, month, day, post):
    # try:
    #     post = Post.published.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404("No Post found.")

    # or

    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    comments = post.comments.filter(active=True)
    form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]

    context = {
        "post": post,
        "comments": comments,
        "form": form,
        "similar_posts": similar_posts,
    }
    return render(request, "blog/post/detail.html", context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # --- send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}'s comments: {cd['comments']}"
            )
            send_mail(subject, message, "gutswillneverhurtanyone@gmail.com", [cd["to"]])
            sent = True

    else:
        form = EmailPostForm()

    context = {"post": post, "form": form, "sent": sent}
    return render(request, "blog/post/share.html", context)


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {"post": post, "form": form, "comment": comment}
    return render(request, "blog/post/comment.html", context)


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            #search_vector = SearchVector("title", weight="A") + SearchVector(
            #    "body", weight="B"
            #)
            #search_query = SearchQuery(query)
            results = (
                Post.published.annotate(
                    similarity=TrigramSimilarity("title", query),
                )
                .filter(similarity__gte=0.1)
                .order_by("-similarity")
            )

    context = {"form": form, "query": query, "results": results}
    return render(request, "blog/post/search.html", context)

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a title{% endblock title %}

{% block content %}

    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{post.get_absolute_url}}">Back to the post</a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}

{% endblock content %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{post.title}}{% endblock title%}

{% block content %}

<h1>{{post.title}}</h1>
<p>
    Published {{post.publish}} by {{post.author}}
</p>
{{post.body|markdown}} 
<p>
    <a href="{% url "blog:post_share" post.id %}">
        Share this post
    </a>
</p>

<h2>Similar Post</h2>
{% for post in similar_posts %}
    <p>
        <a href="{{post.get_absolute_url}}"> {{post.title}} </a>
    </p>
{% empty %}
    There are no similar posts yet.
{% endfor %}

{% with comments.count as total_comments %}
    <h2>
        {{total_comments}} comment{{total_comments|pluralize}}
    </h2>
{% endwith %}

{% for comment in comments %}
    <div class="comment">
        <p class="infor">
            Comment {{forloop.counter}} by {{comment.name}}
            {{comment.created}}
        </p>
        {{comment.body|linebreaks}}
    </div>
{% empty %}
    <p>There are no comments.</p>
{% endfor %}
{% include "blog/post/includes/comment_form.html" %}

{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{post.get_absolute_url}}"> {{post.title}} </a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock title %}

{% block content %}
<h1>My Blog</h1>
{% if tag %}
    <h2>Posts tagged with "{{tag.name}}" </h2>
{% endif %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{post.title}}
    </a>
</h2>
<p class="tags">
    Tags:
    {% for tag in post.tags.all  %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{tag.name}}
        </a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
<p class="date"> 
    Published {{post.publish}} by {{post.author}}
</p>
{{post.body|markdown|truncatechars_html:30}}
{% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock content %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock title %}

{% block content %}

    {% if query %}
        <h1>Posts containing " {{query}} "</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{total_results}} result{{total_results|pluralize}}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{post.get_absolute_url}}">
                    {{post.title}}
                </a>
            </h4>
            {{post.body|markdown|truncatechars_html:12}}
        {% empty %}
        <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{form.as_p}}
            <input type="submit" value="search">
        </form>

    {% endif %}

{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock title %}

{% block content %}
{% if sent %}

<h1>E-mail successfully sent</h1>
<p>
    "{{post.title}}" was successfully sent to {{form.cleaned_date.to}}.
</p>
{% else %}

<h1>Share "{{post.title}}" by e-mail</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Send e-mail">
</form>

{% endif %}
{% endblock content %}